name: boosCooldown
main: cz.boosik.boosCooldown.boosCoolDown
version: 2.1.3 beta
author: boosik
softdepend: [Vault,PermissionsEX]
description: >
             Shortcuts
commands:
  boosCooldowns:
    description: Reload Command for boosCooldown
    usage: |
           /boosCooldowns