name: boosCooldown
main: cz.boosik.boosCooldown.boosCoolDown
version: 1.5.2
author: boosik
description: >
             Shortcuts
commands:
  boosCoolDown:
    description: Reload Command for boosCooldown
    usage: |
           /<command> [reload]