name: boosCooldown
main: cz.boosik.boosCooldown.boosCoolDown
version: 2.9.0
author: boosik
softdepend: [Vault,PermissionsEX]
description: >
             Shortcuts
commands:
  booscooldowns:
    description: Reload command.
    usage: Use /booscooldowns reload, clearcooldowns <player>, clearwarmups <player> or clearuses <player>